In [29]:
import scipy.stats as ss
import numpy as np

In [ ]:
!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.2.0+cu92 (from versions: 1.4.0, 1.4.0+cpu, 1.4.0+cu100, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.6.0+cu92, 1.7.0, 1.7.0+cpu, 1.7.0+cu101, 1.7.0+cu110, 1.7.0+cu92, 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.7.1+cu92, 1.7.1+rocm3.7, 1.7.1+rocm3.8, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111, 1.8.0+rocm3.10, 1.8.0+rocm4.0.1, 1.8.1, 1.8.1+cpu, 1.8.1+cu101, 1.8.1+cu102, 1.8.1+cu111, 1.8.1+rocm3.10, 1.8.1+rocm4.0.1, 1.9.0, 1.9.0+cpu, 1.9.0+cu102, 1.9.0+cu111, 1.9.0+rocm4.0.1, 1.9.0+rocm4.1, 1.9.0+rocm4.2, 1.9.1, 1.9.1+cpu, 1.9.1+cu102, 1.9.1+cu111, 1.9.1+rocm4.0.1, 1.9.1+rocm4.1, 1.9.1+rocm4.2, 1.10.0, 1.10.0+cpu, 1.10.0+cu102, 1.10.0+cu111, 1.10.0+cu113, 1.10.0+roc

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms

In [ ]:
print(torch.__version__)

# Extraer de archivo .tar.gz

In [ ]:
import tarfile

In [ ]:
file = tarfile.open('/content/drive/MyDrive/Colab Notebooks/project0/resources_project0.tar.gz')
file.extractall('/content/drive/MyDrive/Colab Notebooks/project0')
file.close()

# Libraries test

In [ ]:
!python '/content/drive/MyDrive/Colab Notebooks/project0/test.py'

PASS NumPy installed
PASS SciPy installed
PASS matplotlib installed
PASS PyTorch installed
PASS tqdm installed


# Proyecto 0

In [ ]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    
    A = np.random.random([n,1])
    
    return A

In [ ]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A + B

    return A, B, s

In [ ]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(A+B)

    return s

In [ ]:
A = np.array([[1],[2],[3]])
B = np.array([[4],[5],[6]])
norm(A,B)


In [ ]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    inputs=np.transpose(inputs)
    dot_prod = np.matmul(inputs,weights)
    output = np.tanh(dot_prod)
    
    return output

In [ ]:
inputs = np.array([[2],[1]])
weights = np.array([[0.3],[0.7]])
neural_network(inputs,weights)


array([[0.86172316]])

### vectorización de funcion escalar

In [ ]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x<=y: f=x*y
    else:f=x/y
    return f

In [ ]:
vector_function = np.vectorize(scalar_function, otypes=[float])

In [ ]:
x = np.array([1,2,3,4,5]).reshape(-1,1)
y = np.array([2,2,2,3,5]).reshape(-1,1)


In [ ]:
vector_function(x,y)

array([[ 2.  ],
       [ 4.  ],
       [ 1.5 ],
       [ 1.33],
       [25.  ]])

###  debug.py

In [ ]:
!python '/content/drive/MyDrive/Colab Notebooks/project0/debug.py'

3
6
9
15
3
6
9


# Homework 1

## Perceptron without offset

In [ ]:
x = np.array([[1,0],[-1,10],[-1,-1]])
y = np.array([-1,1,1])

In [ ]:
theta = np.array([0,0])

for t in range(10):
  for i in range(3):
    print(f"i: {i}   -   x_i: {x[i]}   -   y_i: {y[i]}   -   theta: {theta}   -   agreement: {y[i]*np.matmul(theta,x[i])} ")
    if y[i]*np.matmul(theta,x[i]) <=0:
      theta += y[i]*x[i]
      

i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [0 0]   -   agreement: 0 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreement: 1 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreement: 1 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreement: 1 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreeme

## Perceptron with offset

In [ ]:
x = np.array([[-4,2],[-2,1],[-1,-1],[2,2],[1,-2]])
y = np.array([1,1,-1,-1,-1])

In [ ]:
theta = np.array([0,0])
theta_o = 0
i_ini = 0 
missclass=[0,0,0,0,0]
for t in range(10):
  for i in range(5):
    if t==0 and i<i_ini:
      continue
    print(f"i: {i}   -   x_i: {x[i]}   -   y_i: {y[i]}   -   theta: {theta}   -   theta_o:{theta_o}   -   agreement: {y[i] * (np.matmul(theta,x[i]) + theta_o )}")
    if (y[i] * (np.matmul(theta,x[i]) + theta_o )) <= 0 :
      theta += y[i]*x[i]
      theta_o += y[i]
      missclass[i] += 1
print(missclass)

i: 0   -   x_i: [-4  2]   -   y_i: 1   -   theta: [0 0]   -   theta_o:0   -   agreement: 0
i: 1   -   x_i: [-2  1]   -   y_i: 1   -   theta: [-4  2]   -   theta_o:1   -   agreement: 11
i: 2   -   x_i: [-1 -1]   -   y_i: -1   -   theta: [-4  2]   -   theta_o:1   -   agreement: -3
i: 3   -   x_i: [2 2]   -   y_i: -1   -   theta: [-3  3]   -   theta_o:0   -   agreement: 0
i: 4   -   x_i: [ 1 -2]   -   y_i: -1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: 8
i: 0   -   x_i: [-4  2]   -   y_i: 1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: 21
i: 1   -   x_i: [-2  1]   -   y_i: 1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: 10
i: 2   -   x_i: [-1 -1]   -   y_i: -1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: -3
i: 3   -   x_i: [2 2]   -   y_i: -1   -   theta: [-4  2]   -   theta_o:-2   -   agreement: 6
i: 4   -   x_i: [ 1 -2]   -   y_i: -1   -   theta: [-4  2]   -   theta_o:-2   -   agreement: 10
i: 0   -   x_i: [-4  2]   -   y_i: 1   -   theta: [-4  2] 

## homework 1.6 perceptron updates

In [ ]:
from math import *

-1.0

In [ ]:
np.set_printoptions(precision=4)
x = np.array([[ cos(pi*1) , 0 , 0 ] ,
              [ 0 , cos(pi*2) , 0 ] ,
              [ 0 , 0 , cos(pi*3) ] 
              ])
y = np.array([1 , 1 , 1])

In [ ]:
theta = np.array([0,0,0])

for t in range(10):
  for i in range(3):
    print(f"i: {i}   -   x_i: {x[i]}   -   y_i: {y[i]}   -   theta: {theta}   -   agreement: {y[i]*np.matmul(theta,x[i])} ")
    if y[i]*np.matmul(theta,x[i]) <=0:
      theta = theta + y[i]*x[i]

i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [0 0 0]   -   agreement: 0.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  0.  0.]   -   agreement: 0.0 
i: 2   -   x_i: [ 0.  0. -1.]   -   y_i: 1   -   theta: [-1.  1.  0.]   -   agreement: 0.0 
i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 2   -   x_i: [ 0.  0. -1.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 2   -   x_i: [ 0.  0. -1.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 2  

# Project 1

In [ ]:
import tarfile
file = tarfile.open('/content/drive/MyDrive/Colab Notebooks/Project1/resources_sentiment_analysis.tar.gz')
file.extractall('/content/drive/MyDrive/Colab Notebooks/Project1')
file.close()

In [ ]:
feature_vector = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
label = np.array([1,-1,1,-1])
theta = np.array([3,2,-1])
theta_0 = 3

In [ ]:
z= (np.matmul(feature_vector,theta)+theta_0)*label
z

array([  7, -19,  31, -43])

In [ ]:
z<1

array([False,  True, False,  True])

In [ ]:
hg = np.zeros(len(z))
hg[z<1]= 1-z[z<1]

In [ ]:
hg

array([ 0., 20.,  0., 44.])

In [ ]:
np.mean(hg)

16.0

In [ ]:
! python '/content/drive/MyDrive/Colab Notebooks/Project1/sentiment_analysis/test.py'

PASS Import project1
PASS Get order 
PASS Hinge loss single 
PASS Hinge loss full 
PASS Perceptron single update 
PASS Perceptron 
PASS Average perceptron 
PASS Pegasos single update 
PASS Pegasos 
FAIL Classify : not implemented
FAIL Classifier accuracy : not implemented
PASS Bag of words 
WARN Bag of words : does not remove stopwords: ['he', 'is', 'on', 'the', 'there', 'to']
PASS Extract bow feature vectors
WARN Extract bow feature vectors : uses binary indicators as features
