In [1]:
import scipy.stats as ss
import numpy as np 
import os 
import sys
import scipy.sparse as sparse

# Extraer de archivo .tar.gz

In [461]:
import tarfile

In [462]:
file = tarfile.open('../Project5/resources_rl.tar.gz')
file.extractall('../Project5')
file.close()

# Proyecto 0

In [ ]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    
    A = np.random.random([n,1])
    
    return A

In [ ]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A + B

    return A, B, s

In [ ]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(A+B)

    return s

In [ ]:
A = np.array([[1],[2],[3]])
B = np.array([[4],[5],[6]])
norm(A,B)


In [ ]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    inputs=np.transpose(inputs)
    dot_prod = np.matmul(inputs,weights)
    output = np.tanh(dot_prod)
    
    return output

In [ ]:
inputs = np.array([[2],[1]])
weights = np.array([[0.3],[0.7]])
neural_network(inputs,weights)


array([[0.86172316]])

### vectorización de funcion escalar

In [ ]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x<=y: f=x*y
    else:f=x/y
    return f

In [ ]:
vector_function = np.vectorize(scalar_function, otypes=[float])

In [ ]:
x = np.array([1,2,3,4,5]).reshape(-1,1)
y = np.array([2,2,2,3,5]).reshape(-1,1)


In [ ]:
vector_function(x,y)

array([[ 2.  ],
       [ 4.  ],
       [ 1.5 ],
       [ 1.33],
       [25.  ]])

###  debug.py

In [ ]:
!python '/content/drive/MyDrive/Colab Notebooks/project0/debug.py'

3
6
9
15
3
6
9


# Homework 1

## Perceptron without offset

In [ ]:
x = np.array([[1,0],[-1,10],[-1,-1]])
y = np.array([-1,1,1])

In [ ]:
theta = np.array([0,0])

for t in range(10):
  for i in range(3):
    print(f"i: {i}   -   x_i: {x[i]}   -   y_i: {y[i]}   -   theta: {theta}   -   agreement: {y[i]*np.matmul(theta,x[i])} ")
    if y[i]*np.matmul(theta,x[i]) <=0:
      theta += y[i]*x[i]
      

i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [0 0]   -   agreement: 0 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreement: 1 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreement: 1 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreement: 1 
i: 1   -   x_i: [-1 10]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 2   -   x_i: [-1 -1]   -   y_i: 1   -   theta: [-1  0]   -   agreement: 1 
i: 0   -   x_i: [1 0]   -   y_i: -1   -   theta: [-1  0]   -   agreeme

## Perceptron with offset

In [ ]:
x = np.array([[-4,2],[-2,1],[-1,-1],[2,2],[1,-2]])
y = np.array([1,1,-1,-1,-1])

In [ ]:
theta = np.array([0,0])
theta_o = 0
i_ini = 0 
missclass=[0,0,0,0,0]
for t in range(10):
  for i in range(5):
    if t==0 and i<i_ini:
      continue
    print(f"i: {i}   -   x_i: {x[i]}   -   y_i: {y[i]}   -   theta: {theta}   -   theta_o:{theta_o}   -   agreement: {y[i] * (np.matmul(theta,x[i]) + theta_o )}")
    if (y[i] * (np.matmul(theta,x[i]) + theta_o )) <= 0 :
      theta += y[i]*x[i]
      theta_o += y[i]
      missclass[i] += 1
print(missclass)

i: 0   -   x_i: [-4  2]   -   y_i: 1   -   theta: [0 0]   -   theta_o:0   -   agreement: 0
i: 1   -   x_i: [-2  1]   -   y_i: 1   -   theta: [-4  2]   -   theta_o:1   -   agreement: 11
i: 2   -   x_i: [-1 -1]   -   y_i: -1   -   theta: [-4  2]   -   theta_o:1   -   agreement: -3
i: 3   -   x_i: [2 2]   -   y_i: -1   -   theta: [-3  3]   -   theta_o:0   -   agreement: 0
i: 4   -   x_i: [ 1 -2]   -   y_i: -1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: 8
i: 0   -   x_i: [-4  2]   -   y_i: 1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: 21
i: 1   -   x_i: [-2  1]   -   y_i: 1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: 10
i: 2   -   x_i: [-1 -1]   -   y_i: -1   -   theta: [-5  1]   -   theta_o:-1   -   agreement: -3
i: 3   -   x_i: [2 2]   -   y_i: -1   -   theta: [-4  2]   -   theta_o:-2   -   agreement: 6
i: 4   -   x_i: [ 1 -2]   -   y_i: -1   -   theta: [-4  2]   -   theta_o:-2   -   agreement: 10
i: 0   -   x_i: [-4  2]   -   y_i: 1   -   theta: [-4  2] 

## homework 1.6 perceptron updates

In [ ]:
from math import *

-1.0

In [ ]:
np.set_printoptions(precision=4)
x = np.array([[ cos(pi*1) , 0 , 0 ] ,
              [ 0 , cos(pi*2) , 0 ] ,
              [ 0 , 0 , cos(pi*3) ] 
              ])
y = np.array([1 , 1 , 1])

In [ ]:
theta = np.array([0,0,0])

for t in range(10):
  for i in range(3):
    print(f"i: {i}   -   x_i: {x[i]}   -   y_i: {y[i]}   -   theta: {theta}   -   agreement: {y[i]*np.matmul(theta,x[i])} ")
    if y[i]*np.matmul(theta,x[i]) <=0:
      theta = theta + y[i]*x[i]

i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [0 0 0]   -   agreement: 0.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  0.  0.]   -   agreement: 0.0 
i: 2   -   x_i: [ 0.  0. -1.]   -   y_i: 1   -   theta: [-1.  1.  0.]   -   agreement: 0.0 
i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 2   -   x_i: [ 0.  0. -1.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 2   -   x_i: [ 0.  0. -1.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 0   -   x_i: [-1.  0.  0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 1   -   x_i: [0. 1. 0.]   -   y_i: 1   -   theta: [-1.  1. -1.]   -   agreement: 1.0 
i: 2  

# Project 1

In [ ]:
import tarfile
file = tarfile.open('/content/drive/MyDrive/Colab Notebooks/Project1/resources_sentiment_analysis.tar.gz')
file.extractall('/content/drive/MyDrive/Colab Notebooks/Project1')
file.close()

In [ ]:
feature_vector = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
label = np.array([1,-1,1,-1])
theta = np.array([3,2,-1])
theta_0 = 3

In [ ]:
z= (np.matmul(feature_vector,theta)+theta_0)*label
z

array([  7, -19,  31, -43])

In [ ]:
z<1

array([False,  True, False,  True])

In [ ]:
hg = np.zeros(len(z))
hg[z<1]= 1-z[z<1]

In [ ]:
! python '/content/drive/MyDrive/Colab Notebooks/Project1/sentiment_analysis/test.py'

PASS Import project1
PASS Get order 
PASS Hinge loss single 
PASS Hinge loss full 
PASS Perceptron single update 
PASS Perceptron 
PASS Average perceptron 
PASS Pegasos single update 
PASS Pegasos 
PASS Classify 
PASS Classifier accuracy 
PASS Bag of words 
PASS Bag of words  stopwords removed
PASS Extract bow feature vectors
PASS Extract bow feature vectors : correct non binary features


In [ ]:
! cd '/content/drive/MyDrive/Colab Notebooks/Project1/sentiment_analysis' && python main.py

theta:[ 0.00508122 -0.265823   -0.08444933 ...  0.01778422  0.01778422
  0.01778422] and accuracy:0.77
Most Explanatory Word Features
['delicious', 'loves', 'great', 'perfect', 'best', 'favorite', 'wonderful', 'excellent', 'tasty', 'thank']


In [ ]:
dicti={'a':1,'b':2,'c':4}

In [ ]:
dicti['d']=len(dicti)

In [ ]:
dicti['b']

2

# Project 2


In [ ]:
! python '/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1/test.py'

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1/test.py", line 8, in <module>
    import softmax
  File "/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1/softmax.py", line 3, in <module>
    import utils
ModuleNotFoundError: No module named 'utils'


In [ ]:

print(os.getcwd())
os.chdir("/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1")
print(os.getcwd())

/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1
/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1


In [ ]:
! python main.py

Figure(640x480)
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    print('Linear Regression test_error =', run_linear_regression_on_MNIST(lambda_factor=1))
  File "main.py", line 38, in run_linear_regression_on_MNIST
    theta = closed_form(train_x_bias, train_y, lambda_factor)
  File "/content/drive/MyDrive/Colab Notebooks/Project2/mnist/part1/linear_regression.py", line 19, in closed_form
    raise NotImplementedError
NotImplementedError


In [ ]:
m=np.array([1,3,2])
n=np.array([4,10,2])
n = n.reshape(3,1)

In [ ]:
print(m, m.shape, "\n")
print(n, n.shape,"\n")
arr =np.array([[3,6,1],[1,1,1],[7,9,7]])
mn = m*n + arr
print(m*n, type(mn), mn.shape , "\n")
inv = np.linalg.inv(mn)
print(inv)

[1 3 2] (3,) 

[[ 4]
 [10]
 [ 2]] (3, 1) 

[[ 4 12  8]
 [10 30 20]
 [ 2  6  4]] <class 'numpy.ndarray'> (3, 3) 

[[ 0.06842105 -0.16578947  0.26052632]
 [ 0.17894737 -0.01052632 -0.12631579]
 [-0.3         0.15        0.05      ]]


In [ ]:
n, d, k = 3, 5, 7
X = np.arange(0, n * d).reshape(n, d)
temp_parameter = 0.2
theta = np.arange(0, k * d).reshape(k, d)
print(X , "\n\n" , theta)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


### cálculo de probabilidades para softmax

In [ ]:

print('transpuesta de X: \n', np.transpose(X) , '\n')
theta_x_tao = (1/temp_parameter) * np.matmul(theta, np.transpose(X)) 
print('theta_x_tao: \n' , theta_x_tao)
c= np.max(theta_x_tao , axis=0)
print('c:', c , '\n')
print('theta_x_tao - c: \n', theta_x_tao - c , '\n')
e_theta_x_tao_c = np.exp( theta_x_tao - c )
print('e_theta_x_tao_c: \n' , e_theta_x_tao_c , '\n')
H = (1 / np.sum(e_theta_x_tao_c, axis=0)) * e_theta_x_tao_c
print(H) 

In [ ]:
y= np.array([0,2,0,1,0])
#H= np.random.randint(9, size=(3,5))
print('y= \n', y , '\n' ,'H:= \n' , H,  '\n')

In [ ]:
sel = H[y, range(len(y))]
H

array([[1, 2, 8, 4, 0],
       [5, 2, 8, 3, 3],
       [5, 1, 6, 0, 4]])

### build a sparse matrix given the rows and columns and data{0,1}

In [ ]:

row  = np.random.randint(9, size=(20,))
col  = np.arange(0,20,1)
data = np.ones((20,))
print(row , '\n' , col , '\n' , data  , '\n')
coo = sparse.coo_matrix((data, (row, col)), shape=(10, 20))
print(coo.toarray())

[1 4 1 8 1 0 7 6 8 4 1 6 8 2 4 2 3 3 4 8] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### use ** to send or receive a variable amount of arguments(dict{'name1':value1, 'name2':value2 ,,,,})

In [ ]:
# receive
def funcion(a1='prueba', **var_params):
  print(a1 ,'  ', var_params , type(var_params))
 

In [ ]:
# send
dicc = {'var1': 1, 'var':'dos', 'var3' : True}
funcion(a1='test', **dicc )

test    {'var1': 1, 'var': 'dos', 'var3': True} <class 'dict'>


### Broadcasting

In [ ]:
a = np.random.randint(0,8, size=(2,4))
b = np.random.randint(0,5,size=(5,4))
print(b, '\n\n') 
b = np.transpose(b).reshape(1,4,5)
print(a , '\n\n' , b,'\n\n' ) 
dif=a[:,:,np.newaxis]-b
print(dif , dif.shape)

[[0 3 0 4]
 [1 3 1 0]
 [0 4 3 4]
 [1 2 0 4]
 [3 4 2 0]] 


[[6 2 0 0]
 [5 7 2 4]] 

 [[[0 1 0 1 3]
  [3 3 4 2 4]
  [0 1 3 0 2]
  [4 0 4 4 0]]] 


[[[ 6  5  6  5  3]
  [-1 -1 -2  0 -2]
  [ 0 -1 -3  0 -2]
  [-4  0 -4 -4  0]]

 [[ 5  4  5  4  2]
  [ 4  4  3  5  3]
  [ 2  1 -1  2  0]
  [ 0  4  0  0  4]]] (2, 4, 5)


In [ ]:
potencia = np.power(dif,2)
potencia

array([[[36, 25, 36, 25,  9],
        [ 1,  1,  4,  0,  4],
        [ 0,  1,  9,  0,  4],
        [16,  0, 16, 16,  0]],

       [[25, 16, 25, 16,  4],
        [16, 16,  9, 25,  9],
        [ 4,  1,  1,  4,  0],
        [ 0, 16,  0,  0, 16]]])

In [ ]:
norm_2 = np.sum(potencia, axis=1)
print(norm_2  , norm_2.shape)

[[53 27 65 41 17]
 [45 49 35 45 29]] (2, 5)


# Unit 3 : Neural Networks 

In [1]:
import torch

In [10]:
from utils import read_pickle_data

In [17]:
train_set, valid_set, test_set = read_pickle_data('Datasets/mnist.pkl.gz')
train_x, train_y = train_set
Ten = torch.tensor(train_x[0:31], dtype=torch.float32)

In [18]:
train_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
Ten.shape

torch.Size([31, 784])

# Homework 4 excercise 3

In [20]:
# condiciones iniciales
theta = np.array([[0.5,0.5],[6,7],[1,4]])
# datos
x = np.resize(np.array([-1,0,4,5,6]),(5,1))

for i in range(8):
    last_theta = np.copy(theta) 
    # E-Step
        # peso_j * Norm(x, theta) 
    p_j_N = theta[0] * ss.norm.pdf(x , loc=theta[1] , scale=np.sqrt(theta[2]))
        #  P(j|i)
    p_j_i =  p_j_N/np.resize(np.sum(p_j_N, axis=1), (5,1))

    # M-Step
        # hat n
    hn = np.sum(p_j_i,axis=0)

        # peso_j
    theta[0] = hn / len(x)
        
        # hat mean
    theta[1] = np.sum( p_j_i * x , axis=0) / hn 

        # square sigma 
    theta[2] = np.sum( p_j_i * (x-theta[1])**2, axis=0) / (hn*1)    # d = 1 
    
    print('Difference = ' , theta-last_theta )



Difference =  [[-0.13696294  0.13696294]
 [-0.86827197 -5.52896851]
 [-0.3844375   2.9670221 ]]
Difference =  [[ 0.06869626 -0.06869626]
 [ 0.00806173 -0.44865677]
 [-0.01594173 -1.08623681]]
Difference =  [[ 0.05716508 -0.05716508]
 [-0.02432825 -0.43724836]
 [ 0.01893001 -1.32369353]]
Difference =  [[ 0.05137038 -0.05137038]
 [-0.04204072 -0.45681416]
 [ 0.02210909 -1.64234325]]
Difference =  [[ 0.04401081 -0.04401081]
 [-0.05027685 -0.45285848]
 [ 0.01882573 -1.88434475]]
Difference =  [[ 0.01569146 -0.01569146]
 [-0.02309593 -0.17512782]
 [ 0.00716525 -0.77895368]]
Difference =  [[ 2.89447906e-05 -2.89447906e-05]
 [-4.80418732e-05 -3.25907954e-04]
 [ 1.58965421e-05 -1.45007699e-03]]
Difference =  [[ 3.38729045e-12 -3.38734596e-12]
 [-2.82280865e-11 -4.23339142e-12]
 [ 1.37382661e-10 -5.55111512e-17]]


In [21]:
#print(0.4 * ss.norm.pdf(x , loc=6 , scale=np.sqrt(1)) , '\n')
#print(0.6 * ss.norm.pdf(x , loc=7 , scale=np.sqrt(4)) , '\n')

print(p_j_N ,'\n')
print(p_j_i ,'\n')
print(hn, '\n')
theta

[[5.51007526e-13 1.93576580e-01]
 [2.10904827e-09 1.93576578e-01]
 [1.38479699e-01 8.22381841e-19]
 [2.93161489e-01 1.69505529e-27]
 [1.38479692e-01 6.39906172e-38]] 

[[2.84645760e-12 1.00000000e+00]
 [1.08951624e-08 9.99999989e-01]
 [1.00000000e+00 5.93864548e-18]
 [1.00000000e+00 5.78198487e-27]
 [1.00000000e+00 4.62093873e-37]] 

[3.00000001 1.99999999] 



array([[ 0.6       ,  0.4       ],
       [ 4.99999998, -0.5       ],
       [ 0.66666676,  0.25      ]])

In [47]:
print('ln(p(D | theta)) = l(D | theta) = ' , np.log(np.product(np.resize(np.sum(p_j_N, axis=1), (5,1)))))

ln(p(D | theta)) = l(D | theta) =  -24.512532330086678


# Project 4

In [7]:
X=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mu= np.array([[1,2,3],[0,2,1]])
V= np.array([0.2, 0.3])
p = np.array([10,20])

n=4
k=2
pjn=p * np.transpose(np.array([ss.multivariate_normal.pdf(x=X , mean= mu[j], cov=V[j]*np.identity(3)) for j in range(k)]))
pji=  pjn / np.resize(np.sum(pjn, axis=1), (n,1))
pji
    


array([[9.99738387e-01, 2.61612682e-04],
       [9.99999855e-01, 1.44731728e-07],
       [3.57596384e-10, 1.00000000e+00],
       [5.29783418e-46, 1.00000000e+00]])

In [65]:
# calculo de mu
mu=np.sum((np.transpose(pji[:,:,np.newaxis], axes=(1,2,0)) * np.transpose(X[:,:,np.newaxis], axes=(2,1,0))), axis=2) / np.resize(nh, (2,1))
mu

array([[10.00078451, 14.00078451, 18.00078451],
       [33.99607502, 37.99607502, 41.99607502]])

In [163]:
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [168]:
X= np.repeat(X[:,:,np.newaxis] , 10 , axis=2)
X_z= np.ones((4,1,10))
X_z= np.repeat(X_z, 3, axis=1 )
X[X%2==0] = X[X%2==0]- X_z[X%2==0]

In [192]:
f=np.array([0,0,0,0,0])
all(f==0)

True

In [1]:
a=(1,2,3,4)
b=a

In [4]:
a=(4,3,2,1)
b


(1, 2, 3, 4)

In [8]:
import time as t

inicio= t.time() 
pjn=p * np.transpose(np.array([ss.multivariate_normal.pdf(x=X , mean= mu[j], cov=V[j]*np.identity(3)) for j in range(k)]))
fin = t.time()
print(fin-inicio)

0.0010025501251220703


# Examples of reinforcement learning 

## V-value iteration example lecture 17-7

In [456]:
V=np.zeros(5)
g= 1/2
T = np.zeros((5,5,3))
i =np.array([h for h in range(5)])
R = np.zeros((5,5,3))
R[4,:,:]=1


In [457]:
T[i,i,0]=1/2
T[[0,4],[1,3],0] = 1/2
T[i[1:4],i[2:],0]=1/4
T[i[1:4],i[:3],0]=1/4


T[i,i,1]=2/3
T[0,0,1]=1/2
T[0,1,1]=1/2
T[i[1:],i[:4],1]=1/3


T[i,i,2]=2/3
T[4,4,2]=1/2
T[4,3,2]=1/2
T[i[:4],i[1:],2]=1/3


In [458]:
for k in range(100):
    V = np.round(np.max(np.sum(T*(R+(g*V)[np.newaxis, : , np.newaxis]), axis=1), axis=1), 4)
V

array([0.0083, 0.025 , 0.1   , 0.4   , 1.6   ])

## Q-value iteration homework 5 

In [402]:
V=np.zeros(5)
g= 0.6
T = np.zeros((6,6,2))
R = np.zeros((6,6,2))
Q = np.zeros((1,6,2))

In [403]:
T[1:6,0:5,0]=np.identity(5)
T[0,0,0]=1

T[[0,4,5],[0,4,5],1]=1
T[[1,2,3],[1,2,3],1]=0.3
T[[1,2,3],[3,4,5],1]=0.7

In [405]:
for s in range(6):
    for sp in range(6):
        if s!=sp:
            R[s,sp,:] = np.abs(s-sp)**(1/3)
        elif s!=0:
            R[s,sp,:] = (s+4)**(-1/2)
        else:
            R[s,sp,:] = 0

In [406]:
Q = np.sum(T * (R+((g*np.max(Q, axis=2))[:,:,np.newaxis])), axis=1)[np.newaxis,:,:]

In [ ]:
for i in range(100):
    Q = np.sum(T * (R+((g*np.max(Q, axis=2))[:,:,np.newaxis])), axis=1)[np.newaxis,:,:]
print(Q)

# Project 5